/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hardware */

#ifndef _Included_Hardware
#define _Included_Hardware
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
